development:
  host: localhost
  database: friendreminder_dev

test:
  host: localhost
  database: friendreminder_test

production:
  host: <%= ENV["MONGOID_HOST"] %>
  port: <%= ENV["MONGOID_PORT"] %>
  username: <%= ENV["MONGOID_USERNAME"] %>
  password: <%= ENV["MONGOID_PASSWORD"] %>
  database: <%= ENV["MONGOID_DATABASE"] %>
