development:
  host: localhost
  database: friendreminder_dev

test:
  host: localhost
  database: friendreminder_test

production:
  host: "ec2-23-22-250-175.compute-1.amazonaws.com"
  port: 27017 
  database: friendreminder_pro
